version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
    - checkout
    - run:
        name: Install Bundler
        command: gem install bundler
    - run:
        name: Bundle Install
        command: bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs=4 --retry=3
    - run:
        name: Rubocop
        command: bundle exec rubocop --parallel

workflows:
  version: 2
  workflow:
    jobs:
    - build
